# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7991027b93b91de60ac2151e5db2f5012b78ea54971a0e454ffd9947999f852db8dfb2ce56e3be860806808f87512e399f3b785d6bc5c95a26be8742eed4cd4

test:
  secret_key_base: 76ba7c023ad58ba06d7d70316b5cff1fe56aede8877ec97a7e15f24744b13b7527d5e1f476faf36817d432247331acc7dbad0f90abbb2a3ea72cb9d55ed9b900

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
